name: BrettFM
favicon: null
layout_spectrum: 0.74391
typography_spectrum: 0.9711196783464402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b49276'
    - '#000000'
    - '#477f9a'
    - '#014e1f'
  brandStrength: 0.1875
  lightness: 0.19595999037846923
  saturation: 0.7087144425604492
  rhythmicContrast: 0.3072941068094224
purpose: []
